title: About HBP
email: hbprice65@gmail.com
description: "Personal portfolio website for Hillel B. Price, Ph.D."
baseurl: ""
url: "https://hbprice65.github.io"
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
# markdown: kramdown
# kramdown:
#   input: GFM
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
